name: Auto Submit

on:
  issues:
    types: [labeled]

jobs:
  autoflow:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ðŸ¤– Agent PR'
    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun i

      - name: Auto submit
        run: bun run submit
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}